### ISSUE TITLE
Error building DM9051 Ethernet Component // Re-Basing onto develop required

### ISSUE THREAD

**Issue by felixhix** [JuergenLeber/home-assistant-optolink#3]
Hi, I have tried the great guide, however the patched Ethernet component no longer seems to be compatible with current ESPHome versions.
I get build errors (due to missing IPv4 attribute mappings):

![Image](https://github.com/user-attachments/assets/c59fe38f-6093-4c54-95fa-15ef1eca68de)

```bash
INFO ESPHome 2025.4.1
INFO Reading configuration /config/esphome/heating-optolink.yaml...
INFO Updating https://github.com/JuergenLeber/esphome@dm9051
INFO Updating https://github.com/JuergenLeber/esphome_vitoconnect@master
...
AttributeError: module 'esphome.config_validation' has no attribute 'ipv4'
```

A re-basing to the current DEV version may be required.

There were further hints in this PR thread:
https://github.com/esphome/esphome/pull/6861

When I use the source from the pull request, build seems to be fine.
ESPHome Version is 2025.4.1.

Thank's in advance. 🙂

**Comment by bmork** [comment]
Looks like your config is referring to an older version of the PR?  This should work with both 2025.4.1 and the current dev branch at the moment:

```yaml
external_components:
  - source: github://pr#6861
    components:
      - ethernet

ethernet:
  type: DM9051
  clk_pin: GPIO07
  mosi_pin: GPIO10
  miso_pin: GPIO03
  cs_pin: GPIO09
  interrupt_pin: GPIO08
  reset_pin: GPIO06
  clock_speed: 20MHz
```

cv.ipv4 was replaced by  cv.ipv4address in esphome 2025.2.0

Hoping that all the external_components part  will be unnecessary with the next release.  Remeber to remove it when the PR is merged!

**Comment by Sleeper85** [comment]
It is no longer possible to compile with `esphome 2025.5.2`, even after a clean build.
It seems that the new component is not downloaded from the PR...

I use this code : 

```YAML
external_components:
  - source: github://pr#6861
    components:
      - ethernet

ethernet:
  id: my_network
  type: DM9051 # W5500
  clk_pin: 7
  mosi_pin: 10
  miso_pin: 3
  cs_pin: 9
  interrupt_pin: 8
  reset_pin: 6
  clock_speed: 20MHz
```

And I have this error : 

```
Failed config

ethernet: [source packages/board/board_ESP32-C3_ETH01-EVO.yaml:56]
  
  Unknown value 'DM9051', valid options are 'LAN8720', 'RTL8201', 'DP83848', 'IP101', 'JL1101', 'KSZ8081', 'KSZ8081RNA', 'W5500', 'OPENETH'.
  id: my_network
  type: DM9051
  clk_pin: 7
  mosi_pin: 10
  miso_pin: 3
  cs_pin: 9
  interrupt_pin: 8
  reset_pin: 6
  clock_speed: 20MHz
```

**Comment by JuergenLeber** [comment]
Finally this is fixed and builds well with the current and newest ESPHome.
